export const mapCoutryCode = {
  Russia: { cod: 'ru', es: 'Rusia' },
  'Saudi Arabia': { cod: 'sa', es: 'Arabia Saudita' },
  Egypt: { cod: 'eg', es: 'Egipto' },
  Uruguay: { cod: 'uy', es: 'Uruguay' },
  Morocco: { cod: 'ma', es: 'Marruecos' },
  Iran: { cod: 'ir', es: 'Iran' },
  Portugal: { cod: 'pt', es: 'Portugal' },
  Spain: { cod: 'es', es: 'Espana' },
  France: { cod: 'fr', es: 'Francia' },
  Australia: { cod: 'au', es: 'Australia' },
  Peru: { cod: 'pe', es: 'Peru' },
  Denmark: { cod: 'dk', es: 'Dinamarca' },
  Argentina: { cod: 'ar', es: 'Argentina' },
  Iceland: { cod: 'is', es: 'Islandia' },
  Croatia: { cod: 'hr', es: 'Croacia' },
  Nigeria: { cod: 'ne', es: 'Nigeria' },
  'Costa Rica': { cod: 'cr', es: 'Costa Rica' },
  Serbia: { cod: 'rs', es: 'Serbia' },
  Brazil: { cod: 'br', es: 'Brazil' },
  Switzerland: { cod: 'ch', es: 'Suiza' },
  Germany: { cod: 'de', es: 'Alemania' },
  Mexico: { cod: 'mx', es: 'Mexico' },
  Sweden: { cod: 'se', es: 'Suecia' },
  'Korea Republic': { cod: 'kr', es: 'Corea del Sur' },
  Belgium: { cod: 'be', es: 'Belgica' },
  Panama: { cod: 'pa', es: 'Panama' },
  Tunisia: { cod: 'tn', es: 'Tunez' },
  England: { cod: 'gb', es: 'Inglaterra' },
  Poland: { cod: 'pl', es: 'Polonia' },
  Senegal: { cod: 'sn', es: 'Senegal' },
  Colombia: { cod: 'co', es: 'Colombia' },
  Japan: { cod: 'jp', es: 'Japon' }
};
